<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
 <?php
 if($route === NULL || $route === 'home'){
    require 'home.phtml';
 } else if($route === 'inscription'){
    require 'register.phtml';
 } else if($route === 'connexion') {
    require 'login.phtml';
 }
 ?> 
</body>
</html>