<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="logic/login.php">
        <h2>Connexion</h2>
    <label for="email">Email :</label>
    <input type="email" name="email" id="email">
    <br><br>
    <label for="password">Mot de passe :</label>
    <input type="password" name="password" id="password">
    <br><br>
    <label for="hash">Mot de passe chiffré :</label>
        <input type="text" name="hash" id="hash">
        <br><br>
    <button type="submit">S'inscrire</button>
</form>
</body>
</html>