<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="logic/register.php">
        <h2>Inscription</h2>
    <label for="first_name">Prénom :</label>
    <input type="text" name="first_name" id="first_name">
    <br><br>
    <label for="last_name">Nom :</label>
    <input type="text" name="last_name" id="last_name">
    <br><br>
    <label for="email">Email :</label>
    <input type="email" name="email" id="email">
    <br><br>
    <label for="password">Mot de passe :</label>
    <input type="password" name="password" id="password">
    <br><br>
    <button type="submit">S'inscrire</button>
</form>
        
    </form>
</body>
</html>